### ISSUE TITLE
レビュー依頼

### ISSUE THREAD

**Issue by shinotaku1997** [shinotaku1997/slatrition#21]

**Comment by tmtkzk0823** [comment]
コメント欄に何も記載が無いので一度お返ししますね。
[issueベースの開発](https://school.runteq.jp/v3/curriculums/graduate_examination/chapters/4)カリキュラムの`レビュー依頼の際の注意点`をよく読み、ご対応していただいた上、再度レビュー依頼をして頂ければと思います。

**Comment by shinotaku1997** [comment]
# 概要
・クックパッドやクラシルなどの大手レシピサイトに掲載されているレシピのカロリーを計算してくれます。
・３大栄養素のP（タンパク質）、F（脂質）、C（炭水化物）の含有量を自動で測定してくれます。
・いつも食事メニューに飽きたけど、カロリー計算するのは面倒臭い！といった時に使えるサービスです。

# 実装予定の機能
* [ ] 会員登録機能
* [ ] パスワードリセット機能
* [ ] ログイン機能
* [ ] マクロ計算機能（OPENAI　APIを使用）
* [ ] 基礎代謝計算
* [ ] 1日の代謝量計算
* [ ] お気に入り機能
* [ ] レビュー(評価)機能
* [ ] 詳細機能
* [ ] 共有機能
* [ ] レシピ保存機能
ーーーーーーーーーーーーーーー
Google認証、LINE認証はMVPリリースではなく本リリース時に実装したいと思います。
ーーーーーーーーーーーーーーー

# 必要なページ
* [ ] TOPページ
* [ ] サイト選択ページ
* [ ] URL入力ページ
* [ ] 栄養素表示ページ
* [ ] ブックマーク機能（myレシピ機能）
* [ ] 残回数ページ
* [ ] コメントページ
* [ ] マイページ
* [ ] アカウント情報ページ
* [ ] メールアドレスページ
* [ ] パスワードリセットページ
* [ ] 利用規約ページ
* [ ] プライバシーポリシーページ
* [ ] 問い合わせページ

**Comment by Tsuchiya2** [comment]
![image](https://github.com/shinotaku1997/slatrition/assets/61481161/915ca84b-1970-4872-ae5f-3a56017e0440)

projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
上記確認できる状態でご提出をお願いいたします。

**Comment by shinotaku1997** [comment]
>projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。

プロジェクトがプライベートになっておりましたので、パブリックに変更しました。失礼いたしました。
ご確認のほど、よろしくお願いいたします。

**Comment by tarakish** [comment]
確認できました。LGTMです！
MVPリリースに向けて開発頑張ってください！
