### ISSUE TITLE
6/9MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by shinotaku1997** [shinotaku1997/slatrition#70]
## 各種情報
slatrition
https://slatrition.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] 会員登録機能
- [ ] パスワードリセット機能
- [ ] ログイン機能
- [ ] マクロ計算機能（カロリー、PFC、ビタミンなど）
- [ ] 基礎代謝計算
- [ ] お気に入り機能
- [ ] レビュー(評価)機能
- [ ] 詳細機能
- [ ] 共有機能

## READMEレビュー時から変更した機能
- [ ] パスワードリセット機能
- [ ] 基礎代謝計算
- [ ] マクロ計算機能（PFC、ビタミンなど）
- [ ] お気に入り機能
- [ ] レビュー(評価)機能
- [ ] 詳細機能
- [ ] 共有機能

## サービスイメージがわかるようなスクリーンショット等
とくに　なし

**Comment by Tsuchiya2** [comment]
https://github.com/shinotaku1997/slatrition/assets/61481161/60c2f2f7-909b-4d5e-9082-5dd5f4367355

エラーが出てしまうようなので確認をいただけますか。

また、現時点で何ができるかをコメント欄にテキストで説明書きをお願いしたいです。

**Comment by shinotaku1997** [comment]
ご確認ありがとうございます。
現時点では、以下の機能を実装しています。
- [ ] ログイン機能
- [ ] アカウント登録機能
- [ ] マクロ計算機能（現時点ではカロリーのみ）

また、対応できるレシピサイトが現在はクックパッドのみです。
https://cookpad.com/recipe/2589170

よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
https://github.com/shinotaku1997/slatrition/assets/61481161/1a4673ad-4957-4158-9a17-ec3cdee3a398

レシピサイトのURLにクックパットのURL貼り付けてみたのですが、カロリーが表示されず...ご確認をお願いします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
